# Configuración para ambiente de producción

# Firebase Service Account para producción
gcp.firebase.service-account=classpath:firebase_service_account_prod.json
gcp.firebase.bucket-name=ispadmin-687ca.appspot.com

# Base de datos para producción
spring.datasource.url=jdbc:mysql://191.101.234.130:3306/ispadmin?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=VFt!03w^P7r9UmIIr9S0TYi5DiW8$bEQ

# Configuración de pagos para producción
custom.username=25993692
custom.password=prodpassword_lMbdOfSl2BeI9WOB1a4Z4mWKL2uFoA3XYrNVYMwUy5RTQ
custom.restApiServerName=https://api.micuentaweb.pe
custom.hashKey=XYCkSo7SjTeWJndQnYXhmpwD3z8DvDebTWYxCeah4XCim

# Configuración OLT para producción (REAL)
olt.service.mock.enabled=false
olt.service.base-url=https://gigafiberperu.smartolt.com/api/
olt.service.api-key=8503d7e652ae44a79869f30bb473c75d

# Logging para producción (mínimo)
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

