package com.dscorp.wispadmin.wispadmin.service.mikrotik

import com.dscorp.wispadmin.wispadmin.data.model.InstallationType
import com.dscorp.wispadmin.wispadmin.data.model.Plan
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test

class PppoeProfileCatalogTest {

    @Test
    fun `profile name derives from plan speeds and not from the commercial name`() {
        assertEquals("GF-200-200", PppoeProfileCatalog.profileName(plan(download = 200, upload = 200)))
        assertEquals("GF-300-300", PppoeProfileCatalog.profileName(plan(download = 300, upload = 300)))
        assertEquals("GF-600-600", PppoeProfileCatalog.profileName(plan(download = 600, upload = 600)))
        assertEquals("GF-1000-1000", PppoeProfileCatalog.profileName(plan(download = 1000, upload = 1000)))
    }

    @Test
    fun `asymmetric plans keep both speeds in the profile name`() {
        assertEquals("GF-80-40", PppoeProfileCatalog.profileName(plan(download = 80, upload = 40)))
    }

    @Test
    fun `rate limit follows the routeros rx slash tx order seen from the router`() {
        assertEquals("200M/200M", PppoeProfileCatalog.rateLimit(plan(download = 200, upload = 200)))
        assertEquals("40M/80M", PppoeProfileCatalog.rateLimit(plan(download = 80, upload = 40)))
        assertEquals("1000M/1000M", PppoeProfileCatalog.rateLimit(plan(download = 1000, upload = 1000)))
    }

    @Test
    fun `plans without usable speeds have no profile`() {
        assertNull(PppoeProfileCatalog.profileName(plan(download = 100, upload = 0)))
        assertNull(PppoeProfileCatalog.profileName(plan(download = 0, upload = 0)))
        assertNull(PppoeProfileCatalog.profileName(null))
        assertNull(PppoeProfileCatalog.rateLimit(plan(download = 100, upload = 0)))
        assertNull(PppoeProfileCatalog.rateLimit(null))
    }

    @Test
    fun `negative speeds are rejected`() {
        assertNull(PppoeProfileCatalog.profileName(plan(download = -1, upload = 100)))
    }

    @Test
    fun `the cut profile is a fixed name outside the plan catalog`() {
        assertEquals("GF-CORTE", PppoeProfileCatalog.CUT_PROFILE)
    }

    @Test
    fun `a profile name is recognised as generated by the catalog`() {
        assertEquals(true, PppoeProfileCatalog.isCatalogProfile("GF-200-200"))
        assertEquals(true, PppoeProfileCatalog.isCatalogProfile("GF-CORTE"))
        assertEquals(false, PppoeProfileCatalog.isCatalogProfile("PLAN 50 SOLES"))
        assertEquals(false, PppoeProfileCatalog.isCatalogProfile(null))
    }

    @Test
    fun `INTERNET 60 with 25 slash 25 maps to GF-25-25`() {
        val plan = Plan(id = 60, name = "INTERNET 60", price = 60.0, downloadSpeed = 25, uploadSpeed = 25)
        assertEquals("GF-25-25", PppoeProfileCatalog.profileName(plan))
        assertEquals("25M/25M", PppoeProfileCatalog.rateLimit(plan))
    }

    @Test
    fun `profile comment includes name type speeds and price`() {
        val plan = Plan(
            id = 54,
            name = "FIBER 200",
            price = 80.0,
            downloadSpeed = 200,
            uploadSpeed = 200,
            type = InstallationType.FIBER,
        )
        assertEquals("FIBER 200 | FIBER | 200/200 Mbps | S/ 80", PppoeProfileCatalog.profileComment(plan))
    }

    @Test
    fun `profile comment is null when the plan cannot derive a profile`() {
        assertNull(PppoeProfileCatalog.profileComment(plan(download = 100, upload = 0)))
        assertNull(PppoeProfileCatalog.profileComment(null))
    }

    @Test
    fun `username is gf plus the subscription id`() {
        assertEquals("gf2338", PppoeProfileCatalog.username(2338))
        assertEquals("gf1", PppoeProfileCatalog.username(1))
        assertNull(PppoeProfileCatalog.username(null))
    }

    private fun plan(download: Int, upload: Int) = Plan(
        id = 1,
        name = "Plan de prueba",
        price = 50.0,
        downloadSpeed = download,
        uploadSpeed = upload
    )
}
