CREATE TABLE IF NOT EXISTS olt_lab_onu (
    sn VARCHAR(64) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL
);

INSERT IGNORE INTO olt_lab_onu (sn, created_at) VALUES
    ('0031C0B6', CURRENT_TIMESTAMP(6)),
    ('12345B4641531C0B6', CURRENT_TIMESTAMP(6)),
    ('ZTEGDC47BFFD', CURRENT_TIMESTAMP(6));
