    location /ispadmin-staging/ws {
        include snippets/websocket-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }

    location /ispadmin-staging/ {
        include snippets/proxy-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }

    location /ispadmin-staging-traffic/ws {
        include snippets/websocket-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }

    location /ispadmin-staging-traffic {
        include snippets/proxy-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }

    location /ispadmin-staging-oltgateway {
        include snippets/proxy-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }

    location /ispadmin-staging-acs {
        include snippets/proxy-backend.conf;
        proxy_pass http://gigafiber_backend_staging;
    }
