ALTER TABLE subscription
    ADD COLUMN is_bimonthly BOOLEAN NOT NULL DEFAULT FALSE;

-- Replace the 12 placeholders with real subscription IDs, then run this UPDATE:
-- UPDATE subscription
-- SET is_bimonthly = TRUE
-- WHERE id IN (
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_1,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_2,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_3,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_4,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_5,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_6,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_7,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_8,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_9,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_10,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_11,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_12
-- );
