SET @exists := (
    SELECT COUNT(*)
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'subscription'
      AND COLUMN_NAME = 'is_bimonthly'
);

SET @sql := IF(
    @exists = 0,
    'ALTER TABLE subscription ADD COLUMN is_bimonthly BOOLEAN NOT NULL DEFAULT FALSE',
    'ALTER TABLE subscription MODIFY COLUMN is_bimonthly BOOLEAN NOT NULL DEFAULT FALSE'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Replace the 12 placeholders with real subscription IDs, then run this UPDATE:
-- UPDATE subscription
-- SET is_bimonthly = TRUE
-- WHERE id IN (
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_1,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_2,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_3,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_4,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_5,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_6,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_7,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_8,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_9,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_10,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_11,
--     TODO_BIMONTHLY_SUBSCRIPTION_ID_12
-- );
