CREATE TABLE IF NOT EXISTS `olt_mgr_onu_optical_daily` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `subscription_id` INT NULL,
  `onu_id` BIGINT NOT NULL,
  `onu_sn` VARCHAR(64) NOT NULL,
  `olt_id` BIGINT NOT NULL,
  `board` INT NOT NULL,
  `port` INT NOT NULL,
  `onu_index` INT NOT NULL,
  `bucket_start` DATETIME(6) NOT NULL,
  `onu_rx_min` DOUBLE NULL,
  `onu_rx_avg` DOUBLE NULL,
  `onu_rx_max` DOUBLE NULL,
  `onu_tx_min` DOUBLE NULL,
  `onu_tx_avg` DOUBLE NULL,
  `onu_tx_max` DOUBLE NULL,
  `olt_rx_min` DOUBLE NULL,
  `olt_rx_avg` DOUBLE NULL,
  `olt_rx_max` DOUBLE NULL,
  `sample_count` INT NOT NULL,
  CONSTRAINT `uk_sh_optical_daily` UNIQUE (`onu_id`, `bucket_start`),
  INDEX `idx_sh_optical_daily_sub_time` (`subscription_id`, `bucket_start`),
  INDEX `idx_sh_optical_daily_onu_time` (`onu_id`, `bucket_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
